"""add attendance_status column

Revision ID: f8b3db43d13f
Revises: 
Create Date: 2025-06-05 18:31:20.204539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b3db43d13f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('training_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_status', sa.String(length=20), nullable=True))
        batch_op.drop_column('attended')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attended', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('attendance_status')

    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
